---
title: "Strings and Factors"
author: "Nidhi Patel"
date: "10/28/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Strings and regex
```{r}
string_vec = c("my", "name", "is", "nidhi")

str_detect(string_vec, "nidh")
str_replace(string_vec, "nidhi", "Nidhi")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun",
  "it will be fun, i think"
)
str_detect(string_vec, "^i think") #the "^" means it's looking at the first part of the string
str_detect(string_vec, "i think$") #"$" after means look for it at the end
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT"
)

str_detect(string_vec, "[Bb]ush") #in brackets to say it can either by capital or lower case b.
```

```{r}
string_vec = c(
  "7th inning stretch",
  "1st half soon to begin, Texas won the toss.",
  "she is 5 feet 4 inches tall",
  "3AM = can't sleep :("
)

str_detect(string_vec, "[0-9][a-zA-Z]") #asking for a number first followed immediately by a number. 
#if I say "^[0-9][a-zA-Z]", it will ask for the #followed by letter at the beginning of the line. ^ is the beginning.
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
)

str_detect(string_vec, "7.11") #the dot should match everything; and it does match the -, :, dot. only the 711 does not have a separation and is false. dot is a SPECIAL CHARACTER 
#if you really only want 7.11, you need to add "\\" before: "7\\.11".
#need two slashes bc slash is also a specual chatacter like the dot. 
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on page [6-7]'
)
#open bracket is also a special character. if you want to detect it you need to have the '\\' before it. 
str_detect(string_vec, "\\[")
```

## Factors

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

factor_vec

as.numeric(factor_vec)
```

what happens if i relevel...?

```{r}
factor_vec = fct_relevel(factor_vec, "male")

factor_vec

as.numeric(factor_vec)
#changed male = 1 from previous code chunk, where male = 2
#fct_recode, fct_reorder, fct_relevel, str_count, extract, locate, remove. google forcats and stringr.
```

## NSDUH -- strings

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

tabl_marj = 
  read_html(url) %>% 
  html_nodes(css = "table") %>% 
  first() %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```

```{r}
data_marj = 
  tabl_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) %>% 
  separate(age_year, into = c("age", "year"), sep = "\\(") %>% 
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)
  ) %>% 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

## NSDUH -- factors

```{r}
data_marj %>% 
  filter(age == "12-17") %>% 
  mutate(State = fct_reorder(State, percent)) %>% 
  #this will take the lowest median value to reorder
  #mutate(State = fct_relevel(State, "Texas")) %>% 
#trying to put this in a better order. This but of code puts texas first. State is being converted from factor to char. Makes texas default. Moves to the front
  ggplot(aes(State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

